language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "curo-financial-technologies-corp"
    token:
      secure: "390f5e2f823df9e13cac6cd75caa35c0a934dab4"
jdk:
- oraclejdk17
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=CURO-Financial-Technologies-Corp_sonarqube-prometheus-exporter
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
